### ISSUE TITLE
multiZoneSetColorZones() does not support CSS (as per LifxLanColor)

### ISSUE THREAD

**Issue by paolotremadio** [futomi/node-lifx-lan#11]
Hi,

I've been trying to use the multiZoneSetColorZones() that should accept as `color` the class `LifxLanColor`.

It looks like the `color` property is not transformed properly as it only accepts `LifxLanColorHSB` objects. I've been trying to use `LifxLanColorCSS` without success.

Example:
```
device.multiZoneSetColorZones({
     start    : 0,
     end      : 8,
     color    :  { css: "#ff0000" },
     duration : 0,
     apply    : 1
   })
```

Error:
```
(node:61955) UnhandledPromiseRejectionWarning: Error: The `color.hue` is required.
    at LifxLanComposer._checkColorValues (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-composer.js:414:12)
    at LifxLanComposer._composePayload501 (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-composer.js:652:29)
    at LifxLanComposer._composePayload (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-composer.js:135:15)
    at LifxLanComposer.compose (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-composer.js:44:33)
    at Promise (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:131:26)
    at new Promise (<anonymous>)
    at LifxLanUdp._requestUnicast (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:118:16)
    at Promise (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:107:9)
    at new Promise (<anonymous>)
    at LifxLanUdp.request (/Users/paolo/Downloads/node-lifx-lan-master/node_modules/node-lifx-lan/lib/lifx-lan-udp.js:92:16)
````

**Comment by futomi** [comment]
Thank you for your feedback. 

The [`multiZoneSetColorZones()`](#LifxLanDevice-multiZoneSetColorZones-method) method did not accept a [`LifxLanColor`](#LifxLanColor-object) object for the `color` parameter even though this document says the method does. The method accepted only a [`LifxLanColorHSB`](#LifxLanColorHSB-object) object.

I updated this module. Now the method accepts a [`LifxLanColor`](#LifxLanColor-object) object for the parameter. That is, the method accepts not only a [`LifxLanColorHSB`](#LifxLanColorHSB-object) object but also a [`LifxLanColorRGB`](#LifxLanColorRGB-object), [`LifxLanColorXyb`](#LifxLanColorXyb-object), and [`LifxLanColorCSS`](#LifxLanColorCSS-object) object.

Try the latest version.

**Comment by paolotremadio** [comment]
It works! One last thing: is there an option to override the brightness of a colour? 
Otherwise: how do you set the brightness of a multi-zone strip?

**Comment by futomi** [comment]
> One last thing: is there an option to override the brightness of a colour?

RGB intrinsically includes the factor of brightness. CSS color based on RGB also does.
Each level in RGB is relevant to brightness. For example, `#110000` is dark red, `#ff0000` is bright red.
As long as you use RGB or CSS color, you can not specify brightness independently.

> Otherwise: how do you set the brightness of a multi-zone strip?

If you want to specify brightness independently, you should use HSB color.

**Comment by paolotremadio** [comment]
That’s what I was thinking. Any chance to module exports the lifx-lan-color.js library? Or to access it using the public api of the package as is.. so I don’t have to implement my own RGB-HSB converter

**Comment by futomi** [comment]
Let me ask same questions:

* What is the lifx-lab-colors library?
* Does it accept brightness with RGB?
* If so, how does it calculate HSB from RGB + brightness? Is the formula open?

I have an idea to calculate HSB from RGB + brightness. But I'm not sure that my idea is compatible with the lifx-lab-colors library.

**Comment by paolotremadio** [comment]
Sorry, that was a typo. I meant: I'd like to use  your lifx-lan-color.js  package to convert RGB to HSB and override the brightness after the conversion has  been calculated. Is that file exported or its API accessible using the main package?

**Comment by futomi** [comment]
Oh, lifx-lan-color.js is my my own. I thought it is LIFX official SDK or something. Sorry not to noticed that. I'll try to implement your request. Give me some time.

**Comment by futomi** [comment]
I added the `brightness` parameter to the [`LifxLanColorCSS`](https://github.com/futomi/node-lifx-lan#LifxLanColorCSS-object) and [`LifxLanColorRGB`](https://github.com/futomi/node-lifx-lan#LifxLanColorRGB-object) object. Try the latest version.

Thank you.

**Comment by paolotremadio** [comment]
It works, thanks! 

Here's how I'm using your package: https://github.com/paolotremadio/homebridge-automation-lifx-colour-palettes
