### ISSUE TITLE
Question - how to create morph effect 

### ISSUE THREAD

**Issue by dman777** [futomi/node-lifx-lan#13]
Wow, thanks for this package. It helps alot with the LAN protocol. 

I have Lifx tiles and I would like to have dark blue and magenta colors morph with each other using the morph effect. 

I was able to successfully use the `lightSetWaveForm` method on my tiles from your example code snippet. But I am still a bit stumped on how to create a morph effect with just two colors from this library. 

Any suggestions?

**Comment by futomi** [comment]
Thank you for your feedback.

The `lightSetWaveForm()` just creates a packet defined in the [LIFX Lan protocol "SetWaveform - 103"](https://lan.developer.lifx.com/docs/light-messages#section-setwaveform-103). Unfortunately, I don't know how to solve your issue and whether the LIFX LAN protocol can solve your issue or not.
