### ISSUE TITLE
Support for firmware effects?

### ISSUE THREAD

**Issue by Djelibeybi** [futomi/node-lifx-lan#16]
Do you have plans to enable support for firmware effects in the LIFX Z and Tile products? Documentation for the LAN protocol implementation is here: https://lan.developer.lifx.com/docs/firmware-effects

I'm trying to find a Node.js library with support to use as the base for a Homebridge plugin to create switches to turn each effect on/off. :)

**Comment by ssmoss** [comment]
Just curious if there are any plans to support these effects? The documentation seems to indicate that "Move" is the only supported one for now though the HTTP API has support for more. I created a ticket asking if the documentation is incomplete or if it is a firmware issue.
