### ISSUE TITLE
No longer working with Node.js 10

### ISSUE THREAD

**Issue by VanCoding** [futomi/node-lifx-lan#2]
Sadly, when running this with Node.js 10, `buffer.readUIntLE(offset, 8)` throws an exception about only accepting byte lengths up to 6.

I don't know the reason for this change, but it's probably to make sure that there are no overflows because JavaScript does not support int64 values.

But since this was never a problem before, I think it's safe work around this instead of switching an int64 library.

**Comment by futomi** [comment]
Sorry to be late. Thank you for your feedback.
Today, I'll try to support Node.js 10.
