### ISSUE TITLE
How to define res_required

### ISSUE THREAD

**Issue by benjivm** [futomi/node-lifx-lan#22]
Hello, I'm wondering if I can specify the [`res_required` and `ack_required`](https://lan.developer.lifx.com/v2.0/docs/header-description#frame-address) parameters on certain calls? Namely light filters and power off commands.

**Comment by futomi** [comment]
For now, this module sets the `res_required` to `1` (except some methods related to the Tile) and the `ack_required` to `0`. This module does not allow to change the parameters.

Why do you need to change the parameters? The power-off command works well without changing them.

**Comment by benjivm** [comment]
I was having issues with the on/off broadcasts, but by adding stronger validation to the requests I was able to solve the problem.

Thanks for your hard work.
