### ISSUE TITLE
Missing dgram dependency

### ISSUE THREAD

**Issue by mloffer** [futomi/node-lifx-lan#23]
Attempting to run this in an Angular application fails due to dgram dependency:

```
ERROR in ./node_modules/node-lifx-lan/lib/lifx-lan.js
Module not found: Error: Can't resolve 'dgram' in 'C:\dev\control\node_modules\node-lifx-lan\lib'
ERROR in ./node_modules/node-lifx-lan/lib/lifx-lan-udp.js
Module not found: Error: Can't resolve 'dgram' in 'C:\dev\control\node_modules\node-lifx-lan\lib'
```

This package appears to have been removed from npm: https://www.npmjs.com/package/dgram

**Comment by futomi** [comment]
Are you trying to run this module on your web browser? This module is not for web front-end applications.

The `dgram` required by this module is not hosted in the npm. It is an [internal module](https://nodejs.org/api/dgram.html) of nodejs. Try this module with nodejs.

**Comment by mloffer** [comment]
Ah, ok. Not for my use-case, then. Thanks.
