### ISSUE TITLE
discover stops working if first calling on different network than the one with lifx devices on it

### ISSUE THREAD

**Issue by bradwbradw** [futomi/node-lifx-lan#24]
So, i have two networks in my office (let's call them A and B.  B has lifx devices set up, A does not).  If I make a call to `discover()` while connected to A, I'll see no devices, which is expected.  But if I change the network to B, and then repeat the `discover()` call, I still won't see any devices, but I'd expect it to find them now that I'm connected to B.  I've even tried setting the library variable to null, and repeating the `require()` call after changing to B, but i get the same result.  I've also tried not only repeating the `required` call, but dereferencing the require cache, and I get the same result. I also tried using https://github.com/sindresorhus/import-fresh, and same result.

Note that if the first discover call happens while connected to B, then I change to A, call discover, then change back to B, the devices show up okay.

It's as if the discover call "locks" somehow to whatever network happens to be connected at the time.

Here's some more system info:

- library version: `0.3.1`
- node version: `v10.16.0`
- OS: Windows 10 Pro (Version 1809)

**Comment by r1ch** [comment]
Know it's a long ol' time since you asked this:

@bradwbradw I think the issue you're seeing is that during the first `discover()` call the library is binding itself to the network

The binding is done during the init call and sets a flag : this._initialized so it won't happen again

**Comment by bradwbradw** [comment]
I added a call to reset the api library whenever it does not find any devices.

Just calling require again and setting the variable like `Lifx = require('node-lifx-lan');` makes the problem go away. Thanks!

**Comment by alexweininger** [comment]
@bradwbradw Was the error you were encountering the same as #38 ?

**Comment by bradwbradw** [comment]
@alexweininger I don't think there was any error
