### ISSUE TITLE
Use LifxLanDevice directly?

### ISSUE THREAD

**Issue by MarcGodard** [futomi/node-lifx-lan#4]
Is it possible to store the device ip and mac then just make calls without the discovery process?

Will attempt it and report back.

**Comment by MarcGodard** [comment]
Doesn't look possible without some reengineering of the lib.

**Comment by futomi** [comment]
> Is it possible to store the device ip and mac then just make calls without the discovery process?

No.
But that is a nice idea.
I'll put the idea to my to-do-list.
Thank you for your feedback.

Futomi

**Comment by MarcGodard** [comment]
@futomi Thanks, I think its a good idea, discovering can take a while sometime, and you have to wait till it finds an already known device.

If I can help with anything let me know. I have a cool app I am working on that could use this feature.

Also thinking of another app to run on the kodi system that will make the lights match the average colors of the movie playing... I think that might make it more of an immersive experience while watching tv and just be awesome.

**Comment by futomi** [comment]
I newly added the [`createDevice()`](https://github.com/futomi/node-lifx-lan#LifxLan-createDevice-method) method to the `LifxLan` object. This method allows you to obtain the `LifxLanDevice` object without the discovery process if you have already known the IPv4 address and the MAC address of the targeted device.

I hope that this method satisfies your demand.

**Comment by MarcGodard** [comment]
@futomi Awesome, thank you very much. This saves me some effort.
