### ISSUE TITLE
No Lights in Device List

### ISSUE THREAD

**Issue by Sawtaytoes** [futomi/node-lifx-lan#8]
For some reason, I'm not seeing any lights show up when I do a `discover`. I have 113 LIFX lights. All of them show up in the Windows Universal app and the LIFX Android app. Surprisingly, the exact same code runs correctly on my Raspberry Pi 3. What's up with that?

Tested using Node v8.8.1 to v8.11.3.

**Comment by ristomatti** [comment]
@Sawtaytoes I suggest to try with firewall disabled if you have one on. LIFX apps need to bind to some UDP port to get the responses back from the lights. If disabling firewall helps then it should be easy to fix by tuning the firewall settings.

**Comment by futomi** [comment]
@ristomatti, thank you for your advice.
@Sawtaytoes, there is another possible reason why the `discover()` method does not work well in your host computer. Does your host computer have multiple network interfaces? If so, the node-lifx-lan possibly does not work well. I'm trying to fix the issue. See the issues #7 for details.

**Comment by futomi** [comment]
I updated the node-lifx-lan. Now it supports multihomed host. Try the latest version (v.0.2.0).

**Comment by Sawtaytoes** [comment]
I tried out node-lifx-lan `0.2.1` in Node `10.7.0` and was unable to see any lights.

I do have multiple network interfaces because of Hyper-V (from installing Docker), and both a physical Ethernet and Wi-Fi adapter on this machine. Docker is not running, only installed. Hyper-V is enabled in the Windows configuration, but not running anything either.

Disabling Windows Defender Firewall on my private network did not show any lights.

The Windows Universal App for LIFX _does_ load the lights so Windows should be able to access them. In the "Allow apps to communicate through Windows Defender Firewall" section, Node.js shows up in the list.

**Comment by Sawtaytoes** [comment]
I figured it out! It's something to do with Docker.

To _fix_ the issue, I had to uninstall Docker. Something about the Ethernet adapter it installs or something else related to it are causing problems. I wonder if it has an internal subnet it designates to itself that is incompatible with my home subnet and prevents multicasting from `node-lifx-lan` because of that.

Do you know what might be the issue now since we can narrow it down to Docker?

**Comment by futomi** [comment]
Though VMware and VirtualBox creates Ethernet adapters too, they don't prevent multicasting. I don't know why the Ethernet adapter of Docker prevents multicasting.

**Comment by Venryx** [comment]
@Sawtaytoes Before you uninstalled Docker, did you try just disabling the Ethernet adapter it installed?

The reason I ask is that the broadcast packets are failing on my network as well, and I'd rather not uninstall the various VPN adapters I have available, but disabling them to test is fine. (I've done so with no improvement, but perhaps uninstalling them all the way would resolve it? My guess is that the cause is actually something else in my case, but I figured it's worth asking -- of whether you tried just disabling the Docker adapter and whether that changed anything.)

**Comment by Sawtaytoes** [comment]
@Venryx It's been so long, I no longer know. I also don't have Docker installed on any of my machines either.
