### ISSUE TITLE
Add SKU to products.json (LIFX Mini variant?)

### ISSUE THREAD

**Issue by danjholt** [futomi/node-lifx-lan#9]
I have a LIFX Mini (productID 59) that's not properly loaded since `products.json` doesn't include its metadata.  However, LIFX doesn't include this product ID in their API documentation.  I'm not sure if this is an updated SKU or variant of LIFX Mini (productID 49). The bulb was purchased as part of their multi-pack so maybe it's defined as a separate product ID?  Let me know if I should include any additional info about the light.

Model # L3A19MC08E26

Here's the payload from `LifxLanParser._parsePayload` (without modifying `products.json`):

```
{ vendorId: 1,
  vendorName: 'LIFX',
  productId: 59,
  productName: '',
  hwVersion: 0,
  features: null }
```

I'm currently working around this by appending the following in `products.json`:
```
{
  "pid": 59,
  "name": "LIFX Mini",
  "features": {
    "color": true,
    "infrared": false,
    "multizone": false
  }
}
```

**Comment by futomi** [comment]
Thank you so much for your feedback. I updated the `products.json`. Try the latest version.
